### ISSUE TITLE
Prophage tools

### ISSUE THREAD

**Issue by ibelalov** [replikation/What_the_Phage#114]
README says:
Proper prophage detection is not implemented (yet) - but a handful of tools report them - so they are mostly identified

What are those tools, other than phigaro? What programs contribute to 'Provirus' column in the reports file?

**Comment by mult1fractal** [comment]
prophage detection tools could be: 
* Phaster
* Virsorter
* Phage_Finder
* ProphET
* Prophinder
* PhiSpy

but I didn't tested/checked them yet. this was our plan for next year

I guess with reports file you mean the  `all_pos_phage_quality_summary.tsv` from [here](https://mult1fractal.github.io/WtP.github.io/Workflow-execution/results/) at the bottom of the page (otherwise please specify or paste your output here).
This is just the output from checkV

**Comment by ibelalov** [comment]
Thanks. Got it

**Comment by ibelalov** [comment]
Thanks. Got it
