### ISSUE TITLE
Add the version tag to the configs

### ISSUE THREAD

**Issue by replikation** [replikation/What_the_Phage#14]
@Stormrider935 
* add the docker version tags to the config file, they are all tagged as latest not 0.1 etc.
* make a test run and push it to master if it works
* also see #10

**Comment by Stormrider935** [comment]
* changed latest to 0.1
* all 0.1 tags are working except virsorter

>rror executing process > 'virsorter_wf:virsorter (1)'

>Caused by:
  Process `virsorter_wf:virsorter (1)` terminated with an error exit status (2)

>Command executed:

 > wrapper_phage_contigs_sorter_iPlant.pl -f POI_draft.fa -db 1 --wdir virsorter --ncpu 8 --data-dir >virsorter-data

>Command exit status:
 > 2

>Command output:
  Bin            : /VirSorter
  Dataset        : VIRSorter
  Input file     : POI_draft.fa
  Db             : 1
  Working dir    : virsorter
  Custom phages  : 
  Data dir       : virsorter-data
  Num CPUs       : 8
  blastp         : blastp
  
>  Started at Mon Nov  4 12:52:26 2019
  Step 0.5 : /VirSorter/Scripts/Step_1_contigs_cleaning_and_gene_prediction.pl VIRSorter virsorter/fasta virsorter/fasta/input_sequences.fna 2 >> virsorter/logs/out 2>> virsorter/logs/err
  	

>Command error:
  Step 1 failed, we stop there: either virsorter/fasta/VIRSorter_prots.fasta or virsorter/fasta/VIRSorter_nett_filtered.fasta were not found

>Work dir:
  /tmp/nextflow-phages-mike/66/7fffd437bfa960f4df54f6ede3b9d3

>Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`


* not sure how to handle because virsorter works with latest build but not with 0.1

**Comment by Stormrider935** [comment]
#### Virsorter version tag 

* I think I found the problem why `virsorter/latest` is working and `virsorter:0.1` not
* the RUN commands are the same but vary in size:

###### `virsorter:latest`
 * `/bin/sh -c conda install -c bioconda mcl=14.137 muscle blast perl-bioperl perl-file-which     hmmer=3.1b2 perl-parallel-forkmanager perl-list-moreutils diamond=0.9.14 && conda clean -a`
* size: 221.9 MB

###### `virsorter:0.1`
* `/bin/sh -c conda install -c bioconda mcl=14.137 muscle blast perl-bioperl perl-file-which     hmmer=3.1b2 perl-parallel-forkmanager perl-list-moreutils diamond=0.9.14 && conda clean -a`
* size : 160.12 MB

* the rest of the image history of `virsorter:latest` and `virsorter:0.1` is the same...so the git repo shouldn't be the problem

**Comment by replikation** [comment]
yeah you need to find out what happend, e.g. try out install versions. E.g some programs have specific versions: mcl=14.137; or rebuild out a new container image from scratch. in any case, make sure not to push until you know it works (because latest is the only working one, maybe its possible to tag the latest to 0.1 and push it?)

**Comment by Stormrider935** [comment]
We will use the docker container from the **virsorter-developer** from now on

`quay.io/biocontainers/virsorter:1.0.6--pl526h516909a_1`

I will push and merge the working workflow
