### ISSUE TITLE
Singularity3.6.1 not found

### ISSUE THREAD

**Issue by hayleyjaywilson** [replikation/What_the_Phage#146]
Hello,
I wonder if you can help? I am following the set up instructions here:
`conda create -n wtp nextflow==20.07.01 singularity==3.6.1`

But I am continually getting the error:
`PackagesNotFoundError: The following packages are not available from current channels:

  - singularity==3.6.1`

I have tried adding numerous other channels and getting the same result. I have also installed the package successfully by omitting the singularity part but of course I need it! Then trying to install it later has not been successful. 
I have tried searching specifically for the singularity version but can't seem to find it. Removing the version from the command also gives the same results.

Please could someone point me in the right direction as this software sounds ideal for what I am looking to do!!

**Comment by replikation** [comment]
Is it also not working if you add the `-c conda-forge` flag to the command? because it sounds like it cant find the package

**Comment by hayleyjaywilson** [comment]
Thanks for the reply.
conda create -n wtp -c conda-forge nextflow==20.07.01 singularity==3.6.1
conda create -n wtp -c bioconda nextflow==20.07.01 singularity==3.6.1

All have the same result as before.

conda search singularity==3.6.1 returns no results

Thanks

**Comment by replikation** [comment]
* you could try to remove the `==3.6.1` for now. i forwarded the question to some conda/singularity users, i use docker myself (which would be the preferred solution to use).

**Comment by hayleyjaywilson** [comment]
Sorry. Same result. Thanks for passing this on. I'll look at the Docker option too.

**Comment by replikation** [comment]
@hayleyjaywilson this is working on our end: `conda create -n wtp -c bioconda Nextflow singularity`

**Comment by hayleyjaywilson** [comment]
Sadly not for me. Must be a problem this end although I can't work out what!

**Comment by hayleyjaywilson** [comment]
Although I have just tried it on my remote server and it has worked straightaway. There must be an issue with my conda setup...

**Comment by hoelzer** [comment]
> conda create -n wtp -c bioconda nextflow singularity

I can confirm that this also works for me but will install a quite old Singularity `singularity-2.4.2`. The Singularity on `conda-forge` is more up-to-date. 

@hayleyjaywilson maybe there i something wrong with your default channel configuration in a file called

```
hoelzerm@sebio04:~$ cat .condarc
channels:
  - conda-forge
  - bioconda
  - r
  - defaults
```

For me, this sometimes causes trouble. You could also try a 2-step approach:

```
conda create -n wtp -c bioconda nextflow
conda activate wtp
conda install -c conda-forge singularity
```

worked for me. Are you on a HPC cluster where you dont have root permissions? If so, I would recommend to ask a sys admin to install Singularity for you instead of using the conda version. For me, the conda-installed Singularity version also causes some trouble sometimes and the best way is a "properly" installed Singularity. But of course you can give the via conda installed Singularity a first try. Otherwiste, something like below might work but needs root rights:


# Singularity

## Install 

Based on: https://github.com/hpcng/singularity/blob/master/INSTALL.md

Besides, nice tutorial about snakemake and singularity integration:
https://reproducibility.sschmeier.com/container/index.html#using-a-singularity-container 

### Update system and dependencies
```
sudo apt-get update && \
  sudo apt-get install -y build-essential \
  libseccomp-dev pkg-config squashfs-tools cryptsetup
```

### Get and install GO language
```
wget https://golang.org/dl/go1.15.3.linux-amd64.tar.gz
sudo tar -C /usr/local -xzf ~/Downloads/go1.15.3.linux-amd64.tar.gz
#add to ~/.profile
export GOPATH=${HOME}/go
export PATH=/usr/local/go/bin:${PATH}:${GOPATH}/bin
# check
go version
curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.21.0
```

### Obtain and install recent Singularity 
```
mkdir -p ${GOPATH}/src/github.com/sylabs && \
  cd ${GOPATH}/src/github.com/sylabs && \
  git clone https://github.com/sylabs/singularity.git && \
  cd singularity
git checkout v3.6.4 # check for new releases
```

```
cd ${GOPATH}/src/github.com/sylabs/singularity && \
  ./mconfig && \
  cd ./builddir && \
  make && \
  sudo make install
```

**Comment by hayleyjaywilson** [comment]
Hi Martin,

Thanks so much for your helpful suggestions. I've been back and checked my condarc file and it is set up pretty much the same as your example. I've tried the two step process and nextflow is no problem but still getting the same error with singularity even specifying the conda-forge chanel. I'm at a loss as to what is up with it - nothing seems to be able to locate it even though it clearly exists!

yes, the other is a HPC cluster. However I have just checked and they already have singularity in the module avail list which is version 3.8
So this may be a solution.
Thanks again for all your help I really appreciate it!!

Hayley
________________________________

**Comment by hoelzer** [comment]
@hayleyjaywilson okay strange... but the ways of `conda` are somtimes... you could maybe try `mamba` instead :) Just install `mamba` via `conda` and then use `mamba` to resolve the dependencies ;) 

But, when you can already load a Singularity module on your HPC this might be even better and you can run WtP in a highly parallel manner. 

good luck!
