### ISSUE TITLE
Uncommited changes?

### ISSUE THREAD

**Issue by mdhishamshaikh** [replikation/What_the_Phage#162]
Hi,
I am trying to setup WtP and I am getting this error. Is it cause changes are being made to the repository right now and I should just wait a bit?

Project `replikation/What_the_Phage` contains uncommitted changes -- Cannot switch to revision: v1.1.0

Thank you.

**Comment by mult1fractal** [comment]
Hey,

That's probably because you changed something in the `replikation/What_the_Phage` repo (local) .. so I think its github related and not to WtP...

you could delete your WtP repo locally and clone it again
`git clone https://github.com/replikation/What_the_Phage.git`
this will give you the newest version of WtP
and this error should not occur

Hope this solves your issue... if not let me know

**Comment by mdhishamshaikh** [comment]
Hi,
So I am working in a conda environment on a HPC. I deleted all the files related to nextflow and singularity, and reinstalled them. It works until the singularity image building step.
I thought the issue was resolved in the latest release? Perhaps not. Would it be possible for you to help me circumvent this and download the singularity database? I could make another "issue" for this, if you prefer.
Thank you.

**Comment by replikation** [comment]
did you try to redownload the images or the image that is not working?. this singularity building issue is sadly related to the singularity itself, not our workflow. you can delete and redownload the ones that fail (the setup o WtP should skip existing images).  I know it's a bit annoying. that's why we added the warning message.

**Comment by mdhishamshaikh** [comment]
Hi,
It took a while. I had to add the $1 and $2 paths myself in download_singularity.sh script. I could download all the images now. 
Though now the databases are not getting downloaded. I'll add another issue and close this one.

Thank you.
