### ISSUE TITLE
Dockerhub link not available?

### ISSUE THREAD

**Issue by joelwwh** [replikation/What_the_Phage#188]
Hi there,

I'm trying to find the dockerhub repo for WtP so I can pull it via singularity into my clusters unix system, but it doesnt appear to be there currently?

**Comment by mult1fractal** [comment]
Yes because there is no WtP docker file. This would be against the design philosophy of using nextflow in combination with Docker.

Every Tool has its own Docker. As the initial problem was that many tools require all different kind of dependencies that would break tools that were already successfully installed.
Therefore no WtP docker exists.


But you could use 
`nextflow run replikation/What_the_Phage -r v1.2.1 --setup -profile local,singularity -work-dir ./work --cachedir ./singularity_images`
to download all the singularity images and then run WtP using `-profile local,singularity` in the normal Nextflow run command to start WtP and using singularity images instead of Docker

Hope I could help

Best,
Mike

**Comment by joelwwh** [comment]
Thanks for the clarification, Mike!
