### ISSUE TITLE
upsetr fails if a txt file is empty

### ISSUE THREAD

**Issue by hoelzer** [replikation/What_the_Phage#30]
I just observed that the R code fails if an input file is empty. 

Example:

```bash
nextflow run phage.nf --fasta test-data/PERVI_draft.fa
```

The output of virsorter is empty. Thus, upsetr code fails with 

```R
Command error:
  Error in read.table(file = file, header = header, sep = sep, quote = quote,  :
    no lines available in input
  Calls: sort -> read.csv -> read.table
  Execution halted
```

**Comment by replikation** [comment]
mh okay, in the R heatmap plot I merge all the outputs into one table-file, containing all the data, so I shouldn't have this issue if files are missing (there is always a header present of the input file). Would this be possible for upsetr? Otherwise, you probably would need to create at least an empty header file to feed an "empty table" into the R script if no file is present?

i mean we can set upsetr output for now to `optional true` to avoid errors for now until its stable?

What do you suggest @hoelzer ?

one could do a solution in R ([check this](https://stackoverflow.com/questions/29467993/how-to-skip-blank-files-in-read-table-in-r))

````R
datalist<-lapply(filenames,function(name){
  x <- try(read.table(paste("M:/files/test1/",name,sep=""),head=FALSE,stringsAsFactors=FALSE,sep="\t"))
  if(inherits(x, "try-error"))
    return(NULL)
  else
    return(x)
})
````

**Comment by hoelzer** [comment]
Yeah I think it should be easily fixable with some R code. You are right, maybe adding some header to the *.txt files could already solve the problem.  Maybe 

```bash
sed -i '1s/^/ID/' file *.txt
```

already solves the issue.

**Comment by hoelzer** [comment]
the upsetr module should work now with 

* any amount of input txt files
* also empty result files

The current output: 
<img width="768" alt="Screenshot 2019-12-13 13 37 41" src="https://user-images.githubusercontent.com/14393703/70804211-cd5a0d00-1dad-11ea-9e19-658b20b0427a.png">

There is only one issue left: numbers are cut off in the left part of the figure. It's a minor thing that I would leave for now. I will set up a new issue for this that we do not forget about it. Also, a PDF or PNG output might be considerable next to the SVG

**Comment by hoelzer** [comment]
@replikation ahh I only just remember that in the previous version we removed all sets with 0 overlaps. I can do this, makes more sense

**Comment by replikation** [comment]
yes please :)
