### ISSUE TITLE
Pre-download for Offline-mode

### ISSUE THREAD

**Issue by gabriellovate** [replikation/What_the_Phage#95]
I am interested in using WTP to search for phages in a large data set of bacterial genomes, but I couldn't understand the benefit of using the --setup option. Is there a performance gain for future use of the tool using this option?

**Comment by replikation** [comment]
* depends on your system, if it can handle downloading all the databases and container while running the workflow you don't need to use it of course
* it's mainly intended as a more convenient "option" for some people to download everything first
   * e.g. download singularity, DBs first and transfer them into the cluster, and then point WtP to these locations 
   * it is also intended for singularity, so you can first build everything and don't need to worry about WtP failing because a singularity image could not be built (singularity are built from docker images and this fails sometimes)

**Comment by gabriellovate** [comment]
Thank you very much for the quick response. Now I understand the purpose of the flag.
